name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # todo remove once fixed https://github.com/actions/setup-node/issues/899
      - name: Enable Corepack before setting up Node
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: yarn
      - run: yarn build
      - run: yarn test
#      - run: yarn lint
